### ISSUE TITLE
Handling open ranges

### ISSUE THREAD

**Issue by pupudu** [tajo/react-range#1]
First of all, thank you for creating this package(and react-movable etc.). The implementation quality is just mind blowing!

As per the issue, is there any plan to support open range values? Let me explain using my actual use case. 

In my scenario, I have two requirements, 
1. The range should be 0-100
2. There should be a way to represent "anything more than 100" and "anything less than 0"

I am not sure if this is feasible, nor if it's worth adding to this library. Let me know your thoughts on this.

Thanks!

**Comment by pupudu** [comment]
Currently I am using a handmade HTML5 based slider to achieve this. The first and last values being the open values. (Notice the `>121` value). See example below
[https://imgur.com/a/kXuAuJY](Example)

**Comment by tajo** [comment]
> First of all, thank you for creating this package(and react-movable etc.). The implementation quality is just mind blowing!

Appreciated!

I am not entirely sure what you are trying to achieve. Can you provide that HTML5 example? Also, what would the updated  API look like? Thanks.

**Comment by websocket98765** [comment]
@pupudu Just test if the current max value equals your max value: `this.values[1] === MAX`. If it does, you can know to use a very high value like 9999999 to achieve an open ended affect when passing the data to your API or whatever is actually changing. (But leave this.values[1] simply set to the MAX value and don't alter it, so that the MAX handle remains on the slider on the far right as desired.
