### ISSUE TITLE
Chrome exception spam on mobile scrolling

### ISSUE THREAD

**Issue by MrKolt01** [tajo/react-range#49]
Chrome exception spam on mobile scrolling after interacting with range component:

![image](https://user-images.githubusercontent.com/20852258/69673234-ee7ee600-10aa-11ea-88ab-765cf9d9988d.png)
![image](https://user-images.githubusercontent.com/20852258/69673336-225a0b80-10ab-11ea-86ad-ee33f95fbed5.png)
![image](https://user-images.githubusercontent.com/20852258/69673272-0191b600-10ab-11ea-85e8-bb7caec0d6ab.png)

**Comment by heilwood** [comment]
@tajo is this bug already fixed?

**Comment by tajo** [comment]
@heilwood Not yet. The problem here is that we use React's `onTouchStart` event and then we `preventDefault` it. We need to use `addEventListener` instead of React event system, so we can make it not passive and the error will go away. It's a (small) breaking API change unfortunately (onTouchStart prop will stop exist).

If somebody wants to open PR, I am happy to help. Otherwise, it might take a month or two for me to loop back.

**Comment by tajo** [comment]
Working on this.
