### ISSUE TITLE
Thumbs and track position when resizing/zooming

### ISSUE THREAD

**Issue by vitorbraga** [tajo/react-range#69]
Hi,
I've been facing an issue that I can reproduce in the Storybook of react-range (https://react-range.netlify.com/?path=/story/range--two-thumbs).
In my application, I have resizable panels and every time I resize it, my Sliders with two thumbs are displaced. It's the same behavior we have when we use the zoom-in/zoom-out for Storybook in the link above.
I would like to know if this is an issue and if this has some fix/workaround.
In my case, it happens only for Ranges with multiple thumbs. Ranges with a single thumb work nicely.

Thanks
Congratulations on the nice lib! :)

**Comment by tajo** [comment]
> In my application, I have resizable panels and every time I resize it, my Sliders with two thumbs are displaced. 

This should work just fine. At least I can't reproduce it in the Storybook.

> zoom-in/zoom-out for Storybook

Yes, this breaks the component but that's different than resizing since the zoom is implemented as a `transform: scale(x)` applied to the whole page. This might be hard to fix since we use absolute positioning for the thumbs. Also, probably not something you would ever use in a production app.

**Comment by dfelber** [comment]
I experience a similar behavior:
When the container width gets changed immediately or on window-resize, everything is fine - but when the width is changed with a transition, the track is updated correctly and the thumb updates its position to the previously correct value.

https://codesandbox.io/s/react-range-dsejs
