### ISSUE TITLE
Add onDragStart and onDragEnd events

### ISSUE THREAD

**Issue by hillia** [tajo/react-range#8]
That way we can fire updates after a user is done interacting with it.

**Comment by tajo** [comment]
What's the use-case?

**Comment by hillia** [comment]
If you have a slow event that needs to trigger off of the slider updating (e.g. an AJAX call, or a chart re-render), it might be better to trigger the update after the click/touch has finished.

You can work around this by debouncing or adding an HOC that listens for clicks/touch, but it would be nice to get it directly from the component.

**Comment by awsmcode** [comment]
You can use isDragged, but an implementation of onDragStart and onDragEnd events would make things much easier.

**Comment by Chris-Slade** [comment]
A workaround for anyone who needs it:
1. Define your thumb or track as a function component. (Thumb to handle specific thumbs being dragged, track to handle any thumb being dragged.)
2. Inside the function component, use `useEffect` to detect when dragging starts or stops:
```javascript
const Thumb = ({ isDragged, handleDragStart, handleDragEnd, ...props }) => {
  useEffect(() => {
    if (isDragged) {
      handleDragStart();
    } else {
      handleDragEnd();
    }
  }, [isDragged]);
  return <ThumbElement />;
};

// ...
<Range
  ...
  renderThumb={({ props, isDragged }) => (
    <Thumb 
      isDragged={isDragged}
      handleDragStart={handleDragStart}
      handleDragEnd={handleDragEnd}
      {...props}
    />
  )}
/>
```

**Comment by tajo** [comment]
I like @Chris-Slade's solution (it would be nice to turn it into an example). Closing this for now.

**Comment by websocket98765** [comment]
Came here to ask about / request something similar: 

AirBnb's rheostate offers `onChange()` and `onUpdate()` events, which is very clean. `onUpdate()` is used to set the state, such as values shown for the min and the max while dragging the slider. `onChange()` is used for 'committing' the value, and is where AJAX requests to an API would go. 

IMHO, the above workaround is very verbose and unclear. I'm not even sure if it's even functionally the same given `onUpdate` is intended to fire during the drag when a value changes while sliding the slider, but `onDragStart` and `onDragEnd` would work differently if they work as their name literally implies. I really appreciate the slider otherwise though!
